BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
DEBUG_ENABLE = no
CONSOLE_ENABLE = no
TAP_DANCE_ENABLE = no
MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
 
UNICODE_ENABLE     = no
UNICDOEMAP_ENABLE  = no


NKRO_ENABLE = yes
#FORCE_NKRO = yes

AUTO_SHIFT_ENABLE = no

